package org.example;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.reporter.ExtentSparkReporter;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;
import org.testng.annotations.*;

public class Project_Luma {
    WebDriver driver;
    ExtentReports reports;
    ExtentTest log;
    @BeforeClass()
    public void extent_reports(){
        reports = new ExtentReports();
        ExtentSparkReporter spark = new ExtentSparkReporter("target/spark.html");
        reports.attachReporter(spark);
    }
    @BeforeMethod()
    public void opening_browser() {
        driver = new ChromeDriver();
        driver.manage().window().maximize();
    }
    /*LOGIN AND LOGOUT FUNCTIONALITY*/
    @Test(priority = 1)
    public void signing_and_signout() throws Exception{
        log = reports.createTest("Sign In & Sign Out");
        driver.get("http://magento.softwaretestingboard.com");
        log.info("selecting sign in option");
        driver.findElement(By.xpath("/html/body/div[2]/header/div[1]/div/ul/li[2]/a")).click();
        log.info("entering email");
        driver.findElement(By.id("email")).sendKeys("tomcat@gmail.com");
        log.info("entering password");
        driver.findElement(By.id("pass")).sendKeys("Tomcat@123");
        log.info("clicking on submit button");
        driver.findElement(By.id("send2")).click();
        Thread.sleep(2000);
        log.info("clicking on welcome button");
        driver.findElement(By.xpath(".//button[@class='action switch']")).click();
        log.info("click on sign out");
        driver.findElement(By.xpath("/html/body/div[2]/header/div[1]/div/ul/li[2]/div/ul/li[3]/a")).click();
    }
    /*SEARCHING AN ITEM*/
    @Test(priority =2)
    public void search(){
        log= reports.createTest("Searching an item");
        driver.get("http://magento.softwaretestingboard.com");
        WebElement search=driver.findElement(By.id("search"));
        Actions enter=new Actions(driver);
        log.info("searching formal pants");
        enter.sendKeys(search,"formal pants").sendKeys(Keys.ENTER).build().perform();
        JavascriptExecutor scroll=(JavascriptExecutor) driver;
        scroll.executeScript("window.scroll(0,500)");
    }
    /*BUYING MULTIPLE ITEM FROM WHAT'S NEW*/
    @Test(priority = 3)
    public void adding_items_in_cart() throws Exception {
        log= reports.createTest("Buying Olivia 1/4 Zip Light Jacket");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting women category");
        driver.findElement(By.xpath(".//span[text()='Women']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting jackets category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath(".//ol[@class='items']/li[1]/a[1]")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='S']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required jacket");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[3]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-167")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-49")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("items added to cart successfully");
    }
    @Test(priority = 4)
    public void removing_items_from_cart() throws Exception{
        log= reports.createTest("Buying Olivia 1/4 Zip Light Jacket");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting women category");
        driver.findElement(By.xpath(".//span[text()='Women']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting jackets category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath(".//ol[@class='items']/li[1]/a[1]")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='S']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required jacket");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[3]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-167")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-49")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(5000);
        log.info("view and edit cart items");
        driver.findElement(By.xpath(".//span[text()='View and Edit Cart']")).click();
        log.info("removing item from cart");
        driver.findElement(By.xpath("//*[@id=\"shopping-cart-table\"]/tbody/tr[2]/td/div/a[2]")).click();
        Thread.sleep(2000);
        log.info("items removed from cart successfully");
    }
    /*BUYING MULTIPLE ITEMS FROM WOMEN'S JACKET SECTION*/
    @Test(priority = 5)
    public void jacket_1() throws Exception{
        log= reports.createTest("Buying Olivia 1/4 Zip Light Jacket");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting women category");
        driver.findElement(By.xpath(".//span[text()='Women']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting jackets category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath(".//ol[@class='items']/li[1]/a[1]")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='S']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required jacket");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[1]/div/div/strong/a")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-167")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-49")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    @Test(priority = 6)
    public void jacket_2() throws Exception{
        log= reports.createTest("Buying Juno Jacket ");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting women category");
        driver.findElement(By.xpath(".//span[text()='Women']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting jackets category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath(".//ol[@class='items']/li[1]/a[1]")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='M']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required jacket");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[2]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-168")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-53")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    @Test(priority = 7)
    public void jacket_3() throws Exception{
        log= reports.createTest("Buying Adrienne Trek Jacket ");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting women category");
        driver.findElement(By.xpath(".//span[text()='Women']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting jackets category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath(".//ol[@class='items']/li[1]/a[1]")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='L']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required jacket");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[6]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-169")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-52")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    /*BUYING MULTIPLE ITEMS FROM WOMEN'S HOODIES  SECTION*/
    @Test(priority = 8)
    public void hoodies_1() throws Exception{
        log= reports.createTest("Buying Circe Hooded Ice Fleece");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting women category");
        driver.findElement(By.xpath(".//span[text()='Women']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting hoodie category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath("//*[@id=\"narrow-by-list\"]/div[1]/div[2]/ol/li[2]/a")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='S']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required hoodie");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[1]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-167")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-52")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    @Test(priority = 9)
    public void hoodies_2() throws Exception{
        log= reports.createTest("Buying Daphne Full-Zip Hoodie  ");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting women category");
        driver.findElement(By.xpath(".//span[text()='Women']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting hoodie category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath("//*[@id=\"narrow-by-list\"]/div[1]/div[2]/ol/li[2]/a")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='M']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required hoodie");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[7]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-168")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-57")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    @Test(priority = 10)
    public void hoodies_3() throws Exception{
        log= reports.createTest("Buying Helena Hooded Fleece");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting women category");
        driver.findElement(By.xpath(".//span[text()='Women']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting hoodie category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath("//*[@id=\"narrow-by-list\"]/div[1]/div[2]/ol/li[2]/a")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='L']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required hoodie");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[3]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-169")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-52")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(4000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    /*BUYING MULTIPLE ITEMS FROM MENS JACKET SECTION*/
    @Test(priority = 11)
    public void mens_jacket_1() throws Exception{
        log= reports.createTest("Buying Proteus Fitness Jackshirt ");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting men category");
        driver.findElement(By.xpath(".//span[text()='Men']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting jackets category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath(".//ol[@class='items']/li[1]/a[1]")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='S']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required jacket");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[1]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-167")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-50")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    @Test(priority = 12)
    public void mens_jacket_2() throws Exception{
        log= reports.createTest("Buying Montana Wind Jacket ");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting men category");
        driver.findElement(By.xpath(".//span[text()='Men']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting jackets category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath(".//ol[@class='items']/li[1]/a[1]")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='M']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required jacket");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[2]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-168")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-58")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    @Test(priority = 13)
    public void mens_jacket_3() throws Exception{
        log= reports.createTest("Buying Lando Gym Jacket  ");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting men category");
        driver.findElement(By.xpath(".//span[text()='Men']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting jackets category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath(".//ol[@class='items']/li[1]/a[1]")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='L']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required jacket");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[7]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-169")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-52")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    /*BUYING MULTIPLE ITEMS FROM MENS HOODIES  SECTION*/
    @Test(priority = 14)
    public void mens_hoodies_1() throws Exception{
        log= reports.createTest("Buying Marco Lightweight Active Hoodie");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting men category");
        driver.findElement(By.xpath(".//span[text()='Men']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting hoodie category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath("//*[@id=\"narrow-by-list\"]/div[1]/div[2]/ol/li[2]/a")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='S']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required hoodie");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[1]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-167")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-53")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    @Test(priority = 15)
    public void mens_hoodies_2() throws Exception{
        log= reports.createTest("Buying Oslo Trek Hoodie");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting men category");
        driver.findElement(By.xpath(".//span[text()='Men']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting hoodie category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath("//*[@id=\"narrow-by-list\"]/div[1]/div[2]/ol/li[2]/a")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='M']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required hoodie");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[6]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-168")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-51")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    @Test(priority = 16)
    public void mens_hoodies_3() throws Exception{
        log= reports.createTest("Buying Abominable Hoodie");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting men category");
        driver.findElement(By.xpath(".//span[text()='Men']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting hoodie category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath("//*[@id=\"narrow-by-list\"]/div[1]/div[2]/ol/li[2]/a")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='L']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required hoodie");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[5]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-169")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-53")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    /*BUYING MULTIPLE ITEMS FROM MENS TEES  SECTION*/
    @Test(priority = 17)
    public void men_tees_1() throws Exception{
        log= reports.createTest("Buying Strike Endurance Tee ");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting men category");
        driver.findElement(By.xpath(".//span[text()='Men']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting tees category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath("//*[@id=\"narrow-by-list\"]/div[1]/div[2]/ol/li[3]/a")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='S']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required tees");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[1]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-167")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-49")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    @Test(priority = 18)
    public void men_tees_2() throws Exception{
        log= reports.createTest("Buying Zoltan Gym Tee  ");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting men category");
        driver.findElement(By.xpath(".//span[text()='Men']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting tees category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath("//*[@id=\"narrow-by-list\"]/div[1]/div[2]/ol/li[3]/a")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='M']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required tees");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[6]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-168")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-50")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    @Test(priority = 19)
    public void men_tees_3() throws Exception{
        log= reports.createTest("Buying Logan HeatTec® Tee   ");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting men category");
        driver.findElement(By.xpath(".//span[text()='Men']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting tees category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath("//*[@id=\"narrow-by-list\"]/div[1]/div[2]/ol/li[3]/a")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='L']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required tees");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[3]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-169")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-49")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    /*BUYING MULTIPLE ITEMS FROM MENS TANKS SECTION*/
    @Test(priority = 20)
    public void men_tanks_1() throws Exception{
        log= reports.createTest("Buying Cassius Sparring Tank ");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting men category");
        driver.findElement(By.xpath(".//span[text()='Men']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting tanks category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath("//*[@id=\"narrow-by-list\"]/div[1]/div[2]/ol/li[4]/a")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='S']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required tanks");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[1]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-167")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-50")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    @Test(priority = 21)
    public void men_tanks_2() throws Exception{
        log= reports.createTest("Buying Tristan Endurance Tank ");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting men category");
        driver.findElement(By.xpath(".//span[text()='Men']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting tanks category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath("//*[@id=\"narrow-by-list\"]/div[1]/div[2]/ol/li[4]/a")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='M']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required tanks");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[11]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-168")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-52")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    @Test(priority = 22)
    public void men_tanks_3() throws Exception{
        log= reports.createTest("Buying Atlas Fitness Tank");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting men category");
        driver.findElement(By.xpath(".//span[text()='Men']")).click();
        log.info("selecting tops");
        driver.findElement(By.xpath(".//a[text()='Tops']")).click();
        log.info("selecting tanks category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath("//*[@id=\"narrow-by-list\"]/div[1]/div[2]/ol/li[4]/a")).click();
        log.info("filtering based on size");
        driver.findElement(By.xpath(".//div[text()='Size']")).click();
        WebElement size=driver.findElement(By.xpath(".//a[@aria-label='L']/div"));
        click.moveToElement(size).click().build().perform();
        log.info("Selecting required tanks");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[2]/div/a/span/span/img")).click();
        log.info("selecting size");
        driver.findElement(By.id("option-label-size-143-item-169")).click();
        log.info("selecting color");
        driver.findElement(By.id("option-label-color-93-item-50")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    /*BUYING MULTIPLE ITEMS FROM GEAR SECTION*/
    @Test(priority = 23)
    public void gear_bag() throws Exception{
        log= reports.createTest("Buying Bag ");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting gear category");
        driver.findElement(By.xpath(".//span[text()='Gear']")).click();
        log.info("selecting bags category");
        driver.findElement(By.xpath(".//a[text()='Bags']")).click();
        log.info("selecting bag style");
        driver.findElement(By.xpath(".//div[text()='Style']")).click();
        driver.findElement(By.xpath("//*[@id=\"narrow-by-list\"]/div[1]/div[2]/ol/li[5]/a")).click();
        log.info("selecting required bag");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[6]/div/a/span/span/img")).click();
        Thread.sleep(3000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    @Test(priority = 24)
    public void gear_Fitness() throws Exception{
        log= reports.createTest("Buying Fitness Equipment");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting gear category");
        driver.findElement(By.xpath(".//span[text()='Gear']")).click();
        log.info("selecting Fitness Equipment category");
        driver.findElement(By.xpath(".//a[text()='Fitness Equipment']")).click();
        log.info("selecting Fitness equipment category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath("//*[@id=\"narrow-by-list\"]/div[1]/div[2]/ol/li[1]/a")).click();
        log.info("selecting required equipment");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[1]/div/a/span/span/img")).click();
        Thread.sleep(5000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    @Test(priority = 25)
    public void gear_watches() throws Exception{
        log= reports.createTest("Buying watch ");
        driver.get("http://magento.softwaretestingboard.com");
        Actions click=new Actions(driver);
        log.info("selecting gear category");
        driver.findElement(By.xpath(".//span[text()='Gear']")).click();
        log.info("selecting watches category");
        driver.findElement(By.xpath(".//a[text()='Watches']")).click();
        log.info("selecting watches category");
        driver.findElement(By.xpath(".//div[text()='Category']")).click();
        driver.findElement(By.xpath("//*[@id=\"narrow-by-list\"]/div[1]/div[2]/ol/li[3]/a")).click();
        log.info("selecting required watch");
        driver.findElement(By.xpath("//*[@id=\"maincontent\"]/div[3]/div[1]/div[3]/ol/li[1]/div/a/span/span/img")).click();
        Thread.sleep(3000);
        log.info("clicking on add to cart ");
        driver.findElement(By.xpath(".//button[@id='product-addtocart-button']")).click();
        Thread.sleep(5000);
        log.info("clicking on cart");
        driver.findElement(By.xpath(".//div[@data-block='minicart']")).click();
        Thread.sleep(2000);
        log.info("proceeding to checkout");
        driver.findElement(By.xpath(".//button[text()='Proceed to Checkout']")).click();
        Thread.sleep(5000);
        log.info("filling details and placing order");
        driver.findElement(By.id("customer-email")).sendKeys("tameem26@gmail.com");
        driver.findElement(By.name("firstname")).sendKeys("tameem");
        driver.findElement(By.name("lastname")).sendKeys("syed");
        driver.findElement(By.name("company")).sendKeys("NA");
        driver.findElement(By.name("street[0]")).sendKeys("kotamitta");
        driver.findElement(By.name("street[1]")).sendKeys("meclines road");
        driver.findElement(By.name("street[2]")).sendKeys("khadeeja street");
        driver.findElement(By.name("city")).sendKeys("nellore");
        WebElement element1=driver.findElement(By.name("region_id"));
        Select region=new Select(element1);
        region.selectByValue("12");
        driver.findElement(By.name("postcode")).sendKeys("524001");
        WebElement element2=driver.findElement(By.name("country_id"));
        Select country=new Select(element2);
        country.selectByValue("US");
        driver.findElement(By.name("telephone")).sendKeys("+911234567890");
        Thread.sleep(5000);
        driver.findElement(By.xpath(".//input[@value='flatrate_flatrate']")).click();
        driver.findElement(By.xpath(".//span[text()='Next']")).click();
        Thread.sleep(9000);
        WebElement button=driver.findElement(By.xpath(".//button[@title='Place Order']"));
        click.moveToElement(button).click().perform();
        Thread.sleep(10000);
        log.info("order successfully placed");
    }
    @AfterMethod()
    public void close() {
        driver.quit();
    }
    @AfterClass()
    public void extent_flush(){
        reports.flush();
    }
}
